experiment_name: diffusion_full_stimuli
output_dir: outputs/diffusion_full_stimuli

# Data
dataset_type: stimuli
data_dir: data/15901Stimuli
train_split: 0.9
batch_size: 32

# UNet
in_channels: 3
image_size: 64
model_channels: 64
channel_mult: [1, 2, 4] 
num_res_blocks: 2
attention_resolutions: [16]
dropout: 0.1

# Diffusion
unconditional: false
noise_process: ddpm
num_timesteps: 1000
beta_schedule: cosine
min_snr_gamma: 5.0
cfg_uncond_prob: 0.0

betavae_config_path: outputs/betavae_full_stimuli_b4_h224x224_z12_hd128/config.json
betavae_ckpt_path: outputs/betavae_full_stimuli_b4_h224x224_z12_hd128/checkpoints/best_ckpt.pt
latent_dim: 12

# Optimizer
lr: 1.0e-4
weight_decay: 0.0
max_grad_norm: 1.0

# Training
num_steps: 2500
log_interval: 50
eval_interval: 50
